/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costumer;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salmonella
 */
public class dashboard extends javax.swing.JFrame {

    String sql;
    Statement stm;
    ResultSet r;
    Connection con;
    String[] data,dataPembayaran;
    DefaultTableModel model,modelPembayaran;
    public String idCostumer,idPaket,nama,kelas,tglPergi,tglPulang,status;
    public String idPaketPmb,namaPmb,TglPergiPmb,TglPulangPmb,HargaPmb,StatusPmb,TanggalSekarang,cari;
    public dashboard() {
        initComponents();
        data = new String[2];
        con = new koneksiApp().getConnect();
//        tabelPaket
        String []judul={"ID","NAMA","HARGA","DESKRIPSI"};
        model = new DefaultTableModel(judul,0);
        tabelPaket.setModel(model);
        tampilkan();
//        tabel Pembayaran
        dataPembayaran = new String[2];
        String []pembayaran={"ID","Nama Reservasi","Tgl Pergi","Tgl Kembali","Harga","Status"};
        modelPembayaran = new DefaultTableModel(pembayaran, 0);
        tabelPembayaran.setModel(modelPembayaran);
        tampilkanPembayaran();
    }

    private void tampilkan() {
        int row = tabelPaket.getRowCount();
        for(int a=0;a<row;a++){
        model.removeRow(0);
        }
        try {
            sql ="SELECT * FROM paket";
            stm = con.createStatement();
            r = stm.executeQuery(sql);
            while(r.next()){
            String data[]={r.getString(1),r.getString(2),r.getString(3),r.getString(4)};
            model.addRow(data);
            }
            stm.close();
            r.close();
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        }
    }
    
    private void tampilkanPembayaran(){
        int row = tabelPembayaran.getRowCount();
        for(int a=0;a<row;a++){
        modelPembayaran.removeRow(0);
        }
        
        try {
            idCostumer = tID.getText();
            sql ="SELECT rsv.id_reservasi, rsv.nama, rsv.tanggal_pergi, rsv.tanggal_pulang,pkt.harga, rsv.status "
                    + "FROM reservasi AS rsv INNER JOIN paket AS pkt ON rsv.id_paket=pkt.id_paket WHERE rsv.id_costumer='"+idCostumer+"'";
             
            stm = con.createStatement();
            r = stm.executeQuery(sql);
            while(r.next()){
            String dataPembayaran[]={r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)};
            modelPembayaran.addRow(dataPembayaran);
            }
            stm.close();
            r.close();
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        }
    }
    
    private void reset(){
        fieldID.setText("");
        fieldNamaPaket.setText("");        
        fieldDeskripsi.setText("");
        fieldHarga.setText("");
        fieldNamaPemesan.setText("");
        fieldKelas.setText("");
        fieldTanggalPergi.setDate(null);
        fieldTanggalPulang.setDate(null);
        fieldCari.setText("");
        fieldIdPEmbayaran.setText("");
        fieldNamaPembayaran.setText("");
        fieldHargaPembayaran.setText("");
        fieldCariPembayaran.setText("");
    }
    public class Tanggal{
        private String getTanggalSekarang(){
            DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            return dateformat.format(date);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldNamaPaket = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldDeskripsi = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        fieldNamaPemesan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldKelas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldTanggalPergi = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        fieldTanggalPulang = new com.toedter.calendar.JDateChooser();
        btnPesan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPaket = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPembayaran = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        fieldNamaPembayaran = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldHargaPembayaran = new javax.swing.JTextField();
        btnbayar = new javax.swing.JButton();
        fieldCariPembayaran = new javax.swing.JTextField();
        btnCariPembayaran = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        fieldIdPEmbayaran = new javax.swing.JTextField();
        btnBatalPmb = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnCtkPmb = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 196, 129));

        TNama.setBackground(new java.awt.Color(51, 196, 129));
        TNama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TNama.setPreferredSize(new java.awt.Dimension(27, 14));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Hallo,");

        jLabel4.setText("ID Paket");

        fieldID.setEditable(false);

        jLabel5.setText("Nama Paket");

        fieldNamaPaket.setEditable(false);

        jLabel6.setText("Harga");

        fieldHarga.setEditable(false);

        jLabel7.setText("Deskripsi");

        fieldDeskripsi.setEditable(false);
        fieldDeskripsi.setColumns(20);
        fieldDeskripsi.setRows(5);
        jScrollPane3.setViewportView(fieldDeskripsi);

        jLabel8.setText("Nama Pemesan");

        jLabel9.setText("Kelas");

        jLabel10.setText("Tanggal Pergi");

        fieldTanggalPergi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fieldTanggalPergiPropertyChange(evt);
            }
        });

        jLabel11.setText("Tanggal Pulang");

        fieldTanggalPulang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fieldTanggalPulangPropertyChange(evt);
            }
        });

        btnPesan.setBackground(new java.awt.Color(249, 186, 19));
        btnPesan.setText("PESAN");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        jLabel1.setText("Paket Tempat Wisata");

        fieldCari.setText("Cari tempat");
        fieldCari.setPreferredSize(new java.awt.Dimension(88, 20));

        btnCari.setBackground(new java.awt.Color(51, 51, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tabelPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPaketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPaket);

        jLabel2.setText("Pembayaran");

        tabelPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabelPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembayaranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPembayaran);

        jLabel12.setText("Nama");

        fieldNamaPembayaran.setEditable(false);

        jLabel13.setText("Harga");

        fieldHargaPembayaran.setEditable(false);

        btnbayar.setBackground(new java.awt.Color(249, 186, 19));
        btnbayar.setText("Bayar");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        fieldCariPembayaran.setText("Cari Pembayaran");

        btnCariPembayaran.setBackground(new java.awt.Color(51, 51, 255));
        btnCariPembayaran.setText("Cari");
        btnCariPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPembayaranActionPerformed(evt);
            }
        });

        jLabel14.setText("ID");

        fieldIdPEmbayaran.setEditable(false);

        btnBatalPmb.setBackground(new java.awt.Color(255, 0, 0));
        btnBatalPmb.setText("Batal Pembayaran");
        btnBatalPmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPmbActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 0, 0));
        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnCtkPmb.setBackground(new java.awt.Color(25, 106, 168));
        btnCtkPmb.setText("Cetak Pembayaran");
        btnCtkPmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtkPmbActionPerformed(evt);
            }
        });

        jLabel15.setText("ID");

        jButton1.setBackground(new java.awt.Color(65, 165, 238));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(TNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldHarga)
                                    .addComponent(fieldNamaPaket)
                                    .addComponent(fieldID)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fieldNamaPemesan)
                                            .addComponent(fieldKelas)
                                            .addComponent(fieldTanggalPergi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldTanggalPulang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane3)
                                            .addComponent(btnPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCtkPmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(287, 287, 287)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCari))
                                .addComponent(btnLogOut))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldCariPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCariPembayaran))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(fieldIdPEmbayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(fieldNamaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldHargaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnbayar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatalPmb)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogOut)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fieldCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldNamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldTanggalPergi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldTanggalPulang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(btnPesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCtkPmb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCariPembayaran)
                                    .addComponent(fieldCariPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldIdPEmbayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldNamaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldHargaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbayar)
                                    .addComponent(btnBatalPmb))))
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPaketMouseClicked
        int i = tabelPaket.getSelectedRow();
        if(i > -1){
        fieldID.setText(model.getValueAt(i, 0).toString());
        fieldNamaPaket.setText(model.getValueAt(i, 1).toString());
        fieldHarga.setText(model.getValueAt(i, 2).toString());
        fieldDeskripsi.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_tabelPaketMouseClicked

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        idCostumer = tID.getText();
        idPaket = fieldID.getText();
        nama = fieldNamaPemesan.getText();
        kelas = fieldKelas.getText();
        status = "Belum Lunas";
        
        sql = "INSERT INTO reservasi VALUES(null,'"+idCostumer+"','"+idPaket+"','"+nama+"','"+kelas+"','"+tglPergi+"','"+tglPulang+"',null,'"+status+"')";
        
        try {
            stm = con.createStatement();
            stm.execute(sql);
            JOptionPane.showMessageDialog(null, "Reservasi berhasil di tambahkan");
            tampilkan();
            tampilkanPembayaran();
            reset();
            stm.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnPesanActionPerformed

    private void fieldTanggalPergiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fieldTanggalPergiPropertyChange
       if(fieldTanggalPergi.getDate()!=null){
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tglPergi = format.format(fieldTanggalPergi.getDate());
        }
    }//GEN-LAST:event_fieldTanggalPergiPropertyChange

    private void fieldTanggalPulangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fieldTanggalPulangPropertyChange
        if(fieldTanggalPulang.getDate()!=null){
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tglPulang = format.format(fieldTanggalPulang.getDate());
        }
    }//GEN-LAST:event_fieldTanggalPulangPropertyChange

    private void tabelPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembayaranMouseClicked
        int i = tabelPembayaran.getSelectedRow();
        if(i > -1){
        fieldIdPEmbayaran.setText(modelPembayaran.getValueAt(i, 0).toString());
        fieldNamaPembayaran.setText(modelPembayaran.getValueAt(i, 1).toString());
        fieldHargaPembayaran.setText(modelPembayaran.getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_tabelPembayaranMouseClicked

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        int row = tabelPembayaran.getSelectedRow();
        String idBayar;
        idBayar = tabelPembayaran.getValueAt(row, 0).toString();        
        StatusPmb = "Lunas";
        Tanggal tgl = new Tanggal();
        
        
        sql = "UPDATE reservasi SET tanggal_bayar='"+tgl.getTanggalSekarang()+"',status='"+StatusPmb+"' WHERE id_reservasi='"+idBayar+"'";
        
        try {
            stm = con.createStatement();
            stm.execute(sql);
            JOptionPane.showMessageDialog(null, "Pembayaran berhasil");
            tampilkanPembayaran();
            reset();
            stm.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnBatalPmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPmbActionPerformed
       int row = tabelPembayaran.getSelectedRow();
       String idBayar;
       idBayar = tabelPembayaran.getValueAt(row, 0).toString();        
       StatusPmb = "Pesanan Batal";
       
       sql = "UPDATE reservasi SET status='"+StatusPmb+"' WHERE id_reservasi='"+idBayar+"'";
        try {
            stm = con.createStatement();
            stm.execute(sql);
            JOptionPane.showMessageDialog(null, "Pembayaran diBatalkan");
            tampilkanPembayaran();
            reset();
            stm.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBatalPmbActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        login lg = new login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        cari = fieldCari.getText();
        int row = tabelPaket.getRowCount();
        for(int a=0;a<row;a++){
        model.removeRow(0);
        }
        try {
            sql ="SELECT * FROM paket WHERE nama_paket like'"+cari+"%' OR harga like'"+cari+"%' OR deskripsi like'"+cari+"%'";
            stm = con.createStatement();
            r = stm.executeQuery(sql);
            while(r.next()){
            String data[]={r.getString(1),r.getString(2),r.getString(3),r.getString(4)};
            model.addRow(data);
            }
            stm.close();
            r.close();
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCariPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPembayaranActionPerformed
        cari = fieldCariPembayaran.getText();
        int row = tabelPembayaran.getRowCount();
        for(int a=0;a<row;a++){
        modelPembayaran.removeRow(0);
        }
        
        try {
            sql ="SELECT rsv.id_reservasi, rsv.nama, rsv.tanggal_pergi, rsv.tanggal_pulang,pkt.harga, rsv.status "
                    + "FROM reservasi AS rsv INNER JOIN paket AS pkt ON rsv.id_paket=pkt.id_paket WHERE  nama like'"+cari+"%' OR tanggal_pergi like'"+cari+"%' OR tanggal_pulang like'"+cari+"%' OR status like'"+cari+"%'";
//             WHERE = rsv.id_costumer='"+idCostumer+"'
            stm = con.createStatement();
            r = stm.executeQuery(sql);
            while(r.next()){
            String dataPembayaran[]={r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)};
            modelPembayaran.addRow(dataPembayaran);
            }
            stm.close();
            r.close();
        } catch (Exception e) {
            System.out.println("Error"+e.getMessage());
        }
    }//GEN-LAST:event_btnCariPembayaranActionPerformed

    private void btnCtkPmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtkPmbActionPerformed
        MessageFormat header = new MessageFormat("Laporan Pembayan");
        MessageFormat footer = new MessageFormat("halaman{0,number,integer}");
        
        try {
           tabelPembayaran.print(JTable.PrintMode.NORMAL,header,footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Tidak Bisa Print Laporan %s %n",e.getMessage());
        }
    }//GEN-LAST:event_btnCtkPmbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reset();
        tampilkanPembayaran();
        tampilkan();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel TNama = new javax.swing.JLabel();
    private javax.swing.JButton btnBatalPmb;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCariPembayaran;
    private javax.swing.JButton btnCtkPmb;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnbayar;
    private javax.swing.JTextField fieldCari;
    private javax.swing.JTextField fieldCariPembayaran;
    private javax.swing.JTextArea fieldDeskripsi;
    private javax.swing.JTextField fieldHarga;
    private javax.swing.JTextField fieldHargaPembayaran;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldIdPEmbayaran;
    private javax.swing.JTextField fieldKelas;
    private javax.swing.JTextField fieldNamaPaket;
    private javax.swing.JTextField fieldNamaPembayaran;
    private javax.swing.JTextField fieldNamaPemesan;
    private com.toedter.calendar.JDateChooser fieldTanggalPergi;
    private com.toedter.calendar.JDateChooser fieldTanggalPulang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static final javax.swing.JLabel tID = new javax.swing.JLabel();
    private javax.swing.JTable tabelPaket;
    private javax.swing.JTable tabelPembayaran;
    // End of variables declaration//GEN-END:variables
}
